### PR TITLE
Fortran-friendly version

### PR DESCRIPTION
**Pull request by karlines**
cfunction extensions for Fortran and F95 users
added printing, saving, loading in utilities

### CODE REVIEW

**Comment by eddelbuettel** [comment]
That looks very nice and clean. I will study more carefully later.  

But can you explain in a few words why we need new functions to read/write dynlibs when that was never needed before with C, C++ and (more basic) Fortran?  Is that a 'nice to have' extension or something that  is needed for f90/f95 ?

**Comment by karlines** [comment]
I have a new package that creates compiled code interfaces to "slow" R functions or differential equation or root solving models (from my own packages). The bottleneck is then the creation of the dyn libs (takes a few seconds), while the applications themselves are 10 to 100 times faster than the original. So it makes sense to save the dynlib for later use.

**Comment by eddelbuettel** [comment]
I know where you are coming from, and people sometimes do that with C++ / Rcpp too.  We usually tell them that that is a bad idea and that a package is better.  (Unless you have dynamic code generation a la Stan / RStan where they do something like this too.)

Do you have a worked example in the help page?  This may be useful to have after all :)

**Comment by karlines** [comment]
I will write an example in the help page - but use dontrun{} 

I have added my package that depends on this on github https://github.com/karlines/ccSolve
- it has a vignette that explains why I did this. 

Of course R-packages are better, but you need to be at least half a nerd to be able to make one - sometimes quick and dirty tricks work much more efficiently...  until a more permanent solution is needed

**Comment by eddelbuettel** [comment]
Why did you close it?  I haven't folded this in yet.  Maybe reopen?

**Comment by eddelbuettel** [comment]
Also, you can just add commits to the same pull request. So we just expand, say, the help page.  So with that I still think we should just reopen this one.

**Comment by karlines** [comment]
I reopened - not yet used to what the buttons mean

**Comment by eddelbuettel** [comment]
Ah, yes, done that a few times too.  Gets to be fun as well once you receive PRs: accidentally closing when you meant to comment etc pp.   

I may only get to this tomorrow but I **really** appreciate that you got back to this, and (from first looks) really high-quality PR.

**Pull request merged**
